language: node_js
node_js:
- '4'
- '5'
- '6'
deploy:
  provider: npm
  email: c.skeppstedt@gmail.com
  api_key:
    secure: Xef8ZPMcafsttBM9d80Z061s1+n6cJ8nv9ngVxvLsgkg+zg1VvlfH+h4SrRo3+HFi1p+6iLIh4L7u7mXEIw9gC7kCCr7MLJn2Sp/KhqY3xualUHpTyH67R5uBGsFze2CNqm+BOhULirAgf8I2Y1hV/k50dP3aNfdCjjrJNxlyu1Wv4dMgX8wRK2LDMXKlCVOyta68mZp8Ku/RRSQ9WheyHSwx/C3TS8elVN0Y1nBU5DekHmElidyDA0XiT8WEiYfybrOil7nUc/cgIqU5LvdStRxD3QTUOv2lUtLnXM9BmIPVAkz35qDkHMw0uJoDgdNlVWHGY/HTavjMJFomP1IMIU7xgErkANFKWioEpSzK/TN5BBISJ/Spupf1DcqzuRuvjt6JUG2Lr4KuN8ZwEz9Vmv4vuYuTAE4fpR923C8kO9goFS0FcV7tarHYasORFGIWXvP0oTznH2PtfEzdzr2Ig5qw4FjglQV60cH6RXqbqpv9xDZBotzb0ryk2wbZdMtU8TAKPYji3ymXMlUE9a76lK0Bju3sOmATGBdLX1Ew62AXKA4pd8/7tpYRnWfT7ysH0t33omKRSDCoQ9XvJws5n/FvVC6yBHltmbIo3OYBctwBDWl0td0oF+3aJNKOb7f6UwhC0rCJMq9VsLv4C7I841L+2UTey624rJC3/SYTHo=
  on:
    tags: true
    repo: cskeppstedt/json-post-process-webpack-plugin
