language: node_js
node_js:
- '10'
- '11'
- '12'
deploy:
  provider: npm
  email: c.skeppstedt@gmail.com
  api_key:
    secure: JAo1+P+IfNmcs3B4+/7UJ0mv2BYnIiLgNBDAWL55p6j/0vVvzl039PMAtTTRdUgIvvSBHIGbO+fK87dNju79nkMyrpTwqFNM+YahTlxAHLtsqL9DkVIx43Pg5z6rZBoVDpqnoV6Z23JMZy5wmJiusiACRm718+/r2QoWzHCWprR3RlvYFfguw+c2CvXXAw7mPC3L3y2GWos/bV8JWq15vcd3/qJDhySBWxrUqGI8beEdinWKwbTv37/4/UzYdD6jGMmGpagW4UD6xUWx0JyHxZMHL0lVVDRTbfXACZc0+KMHUIjaWWiAqwxI/yH9mlN+mRQhEUtlzzqY0wVLNmklpdx2iMs/ABpFQnq00TPN7D9RquS9Xn5GMJiS1gsmmYVLpsFnwKFw769cqgBBgqtSleFeEVKHk1zZmT3SNAt44cCYUWwvkCCLlrWRr6sQAAnM0Wmg7UeDaGtWZXUPTHHdXrXHSEhEQK3eL1gTpuSqLW1/EMeRUFXznxTl7d0KbM73PbJpSl40GO7hvEw+bfyftkWDbYK2R+KOJMiKuwf3CaIpoPTTlIg/9jOfBsNugRmgQgLzHOuLthUmd1pMo1r9mYUKXDJMOhY0r5gYtlGCqFjcP90vNlEwFYAWXMd6DnVHNJFwBzV//7m79DztLmAJULk9ps8SxjxwlY7YKpomuP8=
  on:
    tags: true
    repo: cskeppstedt/json-post-process-webpack-plugin
